Repository codehaus-plexus/plexus-build-api, pull requests merged in 2022-10, with the labels that each got.

#38 use share GHA
  .github/workflows/maven.yml
Labels: maintenance

#37 Convert to JSR 330 component
  pom.xml
  src/main/java/org/sonatype/plexus/build/incremental/DefaultBuildContext.java
Labels: enhancement

#43 change package to org.codehaus.plexus.build
  pom.xml
  src/main/java/org/codehaus/plexus/build/BuildContext.java
  src/main/java/org/codehaus/plexus/build/DefaultBuildContext.java
  src/main/java/org/codehaus/plexus/build/EmptyScanner.java
  src/main/java/org/codehaus/plexus/build/ThreadBuildContext.java
  src/main/resources/org/codehaus/plexus/build/version.properties
  src/test/java/org/codehaus/plexus/build/test/TestFullBuildContext.java
  src/test/java/org/codehaus/plexus/build/test/TestIncrementalBuildContext.java
Labels: breaking
